### ISSUE TITLE
New Skill does not work

### ISSUE THREAD

**Issue by hackketbboy** [DimensionGamers/MU#10]
1. Attack range increase does not affected
Reprocedure: SUM with Aqua Beast and Fire Beast, add point to Fire Beast and open skill inrease linked skill attack range by 1
Try to compare attack range of both skills. Yep! No changed.

2. Poison does not effect in PVP
Reprocedure: SUM with Fire Beast new skill tree line, this build will follow poison.
Worked in PVE
but in PVP (Duel) I can't see it works

**Comment by huesoamz** [comment]
The new debuff skill are not affecting in PVP, are only PVE
